/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package catalogador;

import BibliotecaRIGU.JSimpleDialog;
/**
 *
 * @author murphy
 */
public class pantallaPresentacion extends JSimpleDialog {
    
    /**
     * Creates new form pantallaPresentacion
     */
    public pantallaPresentacion() {
        super();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coleccion_cuadros.png"))); // NOI18N
        jLabel1.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

//

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    /**
     * Asigna la imagen dependiendo del tipo.
     * @param i
     */
    public void setImage (int i){
    if(i==0)
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coleccion_cuadros.png")));
    else if(i==1)
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coleccion_libros.png")));
    else if(i==2)
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coleccion_musica.png")));
    else
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coleccion_videojuegos.png")));
}

}
