/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package catalogador;

import BibliotecaRIGU.JSimpleDialog;
import java.awt.Image;

/**
 * Clase del comparador.
 * @author DiegoBergondo
 */
public class pantallaComparador extends JSimpleDialog {
    
    /**
     * Creates new form pantallaComparador
     */
    public pantallaComparador() {
        super();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();

        setMinimumSize(new java.awt.Dimension(400, 170));
        setPreferredSize(new java.awt.Dimension(400, 170));
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(280, 90));
        jPanel1.setPreferredSize(new java.awt.Dimension(280, 90));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jTextField1.setText("Texto a buscar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 209;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 31, 0, 30);
        jPanel1.add(jTextField1, gridBagConstraints);

        jCheckBox1.setText("Añadir");
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 104, 10, 0);
        jPanel1.add(jCheckBox1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = -4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 22, 0);
        add(jPanel1, gridBagConstraints);

        jPanel2.setMinimumSize(new java.awt.Dimension(230, 182));
        jPanel2.setPreferredSize(new java.awt.Dimension(230, 182));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coleccion_cuadros2.png"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(185, 137));
        jLabel1.setPreferredSize(new java.awt.Dimension(185, 137));
        jLabel1.setSize(new java.awt.Dimension(185, 137));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 6, 27, 6);
        jPanel2.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 6, 22, 24);
        add(jPanel2, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Elemento"));
        jPanel3.setMinimumSize(new java.awt.Dimension(280, 90));
        jPanel3.setPreferredSize(new java.awt.Dimension(280, 90));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nombre", "Autor", "Formato" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 109;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 13, 19, 12);
        jPanel3.add(jComboBox1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 25, 0, 0);
        add(jPanel3, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
        getChangeEvent(evt);        
    }//GEN-LAST:event_jCheckBox1StateChanged

//

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    /**
     * Devuelve el jTextField1
     * @return
     */
    public javax.swing.JTextField getTexto(){
    return this.jTextField1;
}

    /**
     * Asigna al jTextField1 el String introducido como parámetro.
     * @param texto
     */
    public void setTexto(String texto){
    this.jTextField1.setText(texto);
}

    /**
     * Devuelve el jCheckBox1
     * @return
     */
    public javax.swing.JCheckBox getIsAnadir() {
    return jCheckBox1;
}

    /**
     * indica si el jCheckBox1 que determina si está marcada la opción de añadir está marcado o no.
     * @return
     */
    public boolean getAnadir(){
    return jCheckBox1.isSelected(); 
}

    /**
     *
     * @param anadir
     */
    public void setAnadir(boolean anadir){
    if((anadir && !this.jCheckBox1.isSelected()) || !anadir && this.jCheckBox1.isSelected())
        this.jCheckBox1.doClick();
}

    /**
     * Devuelve el jComboBox1.
     * @return
     */
    public javax.swing.JComboBox getElemento(){
    return this.jComboBox1;
}

    /**
     * Asigna al jLabel1 la imagen introducida por parámetro.
     * @param imagen
     */
    public void setImagen(Image imagen) {
    Image captura = imagen.getScaledInstance(185, 137, Image.SCALE_DEFAULT);
    this.jLabel1.setIcon(new javax.swing.ImageIcon(captura));
}

    /**
     * Muestra la imagen por defecto.
     */
    public void setImagenDefault() {
    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/no-image-icon3.png")));
}

    /**
     * Asigna la imagen dependiendo del tipo.
     * @param i
     */
    public void setImage (int i){
    if(i==0)
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coleccion_cuadros2.png")));
    else if(i==1)
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coleccion_libros2.png")));
    else if(i==2)
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coleccion_musica2.png")));
    else
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coleccion_videojuegos2.png")));
}

}
