/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package catalogador;

import BibliotecaRIGU.JSimpleDialog;

/**
 * Clase de la segunda pantalla de datos del artículo.
 * @author DiegoBergondo
 */
public class pantallaDescripcion2 extends JSimpleDialog {
    

    /**
     * Creates new form pantallaDescripcion2
     */
    public pantallaDescripcion2() {
        super();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(335, 450));
        setMinimumSize(new java.awt.Dimension(335, 450));
        setPreferredSize(new java.awt.Dimension(335, 450));
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(330, 250));
        jPanel1.setPreferredSize(new java.awt.Dimension(330, 250));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jTextField1.setText("Precio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 15, 0, 0);
        jPanel1.add(jTextField1, gridBagConstraints);

        jTextField2.setText("Anterior dueño");
        jTextField2.setMinimumSize(new java.awt.Dimension(280, 26));
        jTextField2.setPreferredSize(new java.awt.Dimension(280, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 15, 0, 13);
        jPanel1.add(jTextField2, gridBagConstraints);

        jTextField3.setText("Forma de pago");
        jTextField3.setMinimumSize(new java.awt.Dimension(280, 26));
        jTextField3.setPreferredSize(new java.awt.Dimension(280, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 15, 28, 13);
        jPanel1.add(jTextField3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = -123;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jPanel1, gridBagConstraints);

        jPanel2.setMinimumSize(new java.awt.Dimension(330, 250));
        jPanel2.setPreferredSize(new java.awt.Dimension(330, 250));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado"));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Roto", "Gastado", "Aceptable", "Nuevo" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel6.add(jComboBox3, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 27, 0, 30);
        jPanel2.add(jPanel6, gridBagConstraints);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de compra"));
        jPanel5.setPreferredSize(new java.awt.Dimension(280, 89));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = -12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 31, 29, 0);
        jPanel5.add(jComboBox1, gridBagConstraints);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = -17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 6, 29, 0);
        jPanel5.add(jComboBox2, gridBagConstraints);

        jSpinner1.setMinimumSize(new java.awt.Dimension(60, 26));
        jSpinner1.setPreferredSize(new java.awt.Dimension(60, 26));
        jSpinner1.setValue(2000);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 6, 0, 25);
        jPanel5.add(jSpinner1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 27, 17, 30);
        jPanel2.add(jPanel5, gridBagConstraints);

        jPanel3.setMinimumSize(new java.awt.Dimension(150, 120));
        jPanel3.setPreferredSize(new java.awt.Dimension(150, 120));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sad.png"))); // NOI18N
        jPanel3.add(jLabel2, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 88, 0, 0);
        jPanel2.add(jPanel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 61;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 0);
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        if(this.getEstado().getSelectedItem().toString().equalsIgnoreCase("Roto"))
                this.cambiarIcon(0);
        if(this.getEstado().getSelectedItem().toString().equalsIgnoreCase("Gastado"))
                this.cambiarIcon(1);
        if(this.getEstado().getSelectedItem().toString().equalsIgnoreCase("Aceptable"))
                this.cambiarIcon(2);
        else if(this.getEstado().getSelectedItem().toString().equalsIgnoreCase("Nuevo"))
                this.cambiarIcon(3);
    }//GEN-LAST:event_jComboBox3ActionPerformed

//

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    /**
     * Devuelve el jTextField1.
     * @return
     */
    public javax.swing.JTextField getPrecio(){
        return this.jTextField1;
    }
    
    /**
     * Asigna al jTextField el valor que le llega como parámetro.
     * @param precio
     */
    public void setPrecio(int precio){
        this.jTextField1.setText(String.valueOf(precio));
    }
    
    /**
     * Asigna al jTextField1 el texto del String que le llega como parámetro.
     * @param tDefault
     */
    public void setPrecio(String tDefault){
        this.jTextField1.setText(tDefault);
    }
    
    /**
     * Devuelve el jTextField2.
     * @return
     */
    public javax.swing.JTextField getAntDueno(){
        return this.jTextField2;
    }
    
    /**
     * Asigna al jTextField2 el texto del String que le llega como parámetro.
     * @param aDueno
     */
    public void setAntDueno(String aDueno){
        this.jTextField2.setText(aDueno);
    }
    
    /**
     * Devuelve el jTextField3.
     * @return
     */
    public javax.swing.JTextField getFPago(){
        return this.jTextField3;
    }
    
    /**
     * Asigna al jTextField3 el texto del String que le llega como parámetro.
     * @param fPago
     */
    public void setFPago(String fPago){
        this.jTextField3.setText(fPago);
    }
    
    /**
     * Devuelve el jComboBox3.
     * @return
     */
    public javax.swing.JComboBox getEstado(){
        return this.jComboBox3;
    }
    
    /**
     * Selecciona una opción del jComboBox3 dependiendo del valor del String que llega como parámetro.
     * @param estado
     */
    public void setEstado(String estado){
        int i=0;
        if(estado.equals("Gastado"))
            i=1;
        else if(estado.equals("Aceptable"))
            i=2;
        else if(estado.equals("Nuevo"))
            i=3;
        this.jComboBox3.setSelectedIndex(i);
        cambiarIcon(i);    
    }
    
    /**
     * Devuelve el jComboBox1.
     * @return
     */
    public javax.swing.JComboBox getFechaDia(){
        return jComboBox1; 
    }
    
    /**
     * Selecciona una opción del jComboBox1 dependiendo del valor que llega como parámetro.
     * @param dia
     */
    public void setFechaDia(int dia){
        jComboBox1.setSelectedIndex(dia-1);
    }
        
    /**
     * Devuelve el jComboBox2.
     * @return
     */
    public javax.swing.JComboBox getFechaMes(){
        return jComboBox2; 
    }
    
    /**
     * Selecciona una opción del jComboBox2 dependiendo del valor que llega como parámetro.
     * @param mes
     */
    public void setFechaMes(int mes){
        jComboBox2.setSelectedIndex(mes);
    }
            
    /**
     * Devuelve el jSpinner1.
     * @return
     */
    public javax.swing.JSpinner getFechaAno(){
        return jSpinner1; 
    }
    
    /**
     * Asigna al jSpinner1 el valor que le llega como parámetro.
     * @param ano
     */
    public void setFechaAno(int ano){
        this.jSpinner1.setValue(ano); 
    }
    
    /**
     * Asigna al jLabel2 una imagen dependiendo del valor que llega como parámetro.
     * @param i
     */
    private void cambiarIcon(int i){
        if(i==0)
            this.jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sad.png")));
        else if(i==1)
            this.jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sick.png")));
        else if(i==2)
            this.jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/confused.png")));
        else
            this.jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/in-love.png")));
    }

}
