/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package catalogador;

import BibliotecaRIGU.JSimpleDialog;

/**
 * Clase de la última GUI de datos del artículo.
 * @author DiegoBergondo
 */
public class pantallaDescripcion3 extends JSimpleDialog {
    
    /**
     * Creates new form pantallaDescripcion3
     */
    public pantallaDescripcion3() {
        super();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel5 = new javax.swing.JPanel();
        jSlider4 = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(350, 400));
        setMinimumSize(new java.awt.Dimension(350, 400));
        setPreferredSize(new java.awt.Dimension(350, 400));
        setLayout(new java.awt.GridBagLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Precio medio cuadros que quiero"));
        jPanel5.setMinimumSize(new java.awt.Dimension(350, 120));
        jPanel5.setPreferredSize(new java.awt.Dimension(350, 120));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jSlider4.setMaximum(1000);
        jSlider4.setValue(500);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 290;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 12, 0, 0);
        jPanel5.add(jSlider4, gridBagConstraints);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setMinimumSize(new java.awt.Dimension(130, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 112, 13, 0);
        jPanel5.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = -12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 0, 6);
        add(jPanel5, gridBagConstraints);
        jPanel5.getAccessibleContext().setAccessibleName("");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad de cuadros a la venta"));
        jPanel6.setMinimumSize(new java.awt.Dimension(350, 120));
        jPanel6.setPreferredSize(new java.awt.Dimension(350, 120));
        jPanel6.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 308;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 12, 0, 8);
        jPanel6.add(jProgressBar2, gridBagConstraints);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setMinimumSize(new java.awt.Dimension(130, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 112, 24, 0);
        jPanel6.add(jLabel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = -12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 5, 6);
        add(jPanel6, gridBagConstraints);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Precio medio cuadros que tengo"));
        jPanel1.setMinimumSize(new java.awt.Dimension(350, 120));
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 120));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jSlider1.setMaximum(1000);
        jSlider1.setValue(500);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 290;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 12, 0, 0);
        jPanel1.add(jSlider1, gridBagConstraints);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setMinimumSize(new java.awt.Dimension(130, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 112, 18, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 6);
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

//

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider4;
    // End of variables declaration//GEN-END:variables

    /**
     * Asigna al borde del primer recuadro el String introducido como parámetro.
     * @param titulo
     */
    public void setTitulo1(String titulo){
    this.jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(titulo));
}

    /**
     * Asigna al borde del segundo recuadro el String introducido como parámetro.
     * @param titulo
     */
    public void setTitulo2(String titulo){
    this.jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(titulo));
}

    /**
     * Asigna al borde del tercer recuadro el String introducido como parámetro.
     * @param titulo
     */
    public void setTitulo3(String titulo){
    this.jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(titulo));
}

    /**
     * Asigna a jLabel1 y jSlider1 el valor de la media que se tiene, que llegará como parámetro.
     * @param media
     */
    public void setMediaTengo(int media){
    this.jLabel1.setText(String.valueOf(media));
    this.jSlider1.setValue(media);
}

    /**
     * Asigna a jLabel12 y jSlider4 el valor de la media que se quiere, que llegará como parámetro.
     * @param media
     */
    public void setMediaQuiero(int media){
    this.jLabel2.setText(String.valueOf(media));
    this.jSlider4.setValue(media);
}

    /**
     * Asigna a jLabel3 y jProgressBar2 el valor de la media que de lo se vende, que llegará como parámetro.
     * @param media
     */
    public void setMediaVenta(int media){
    this.jLabel3.setText(String.valueOf(media));
    this.jProgressBar2.setValue(media);
}

}