/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package catalogador;

/**
 * Clase de la primera extensión de pantalla del selector de tipo.
 * @author DiegoBergondo
 */
public class pantallaSeleccionA extends pantallaSeleccion {
    
    /**
     * Creates new form pantallaSeleccion
     */
    public pantallaSeleccionA() {
        super();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(670, 640));
        setMinimumSize(new java.awt.Dimension(670, 640));
        setPreferredSize(new java.awt.Dimension(670, 640));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(700, 300));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 300));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 300));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/chooseone.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 21, 6, 19);
        jPanel1.add(jLabel1, gridBagConstraints);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 680, 206));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setMaximumSize(new java.awt.Dimension(700, 200));
        jPanel3.setMinimumSize(new java.awt.Dimension(700, 200));
        jPanel3.setPreferredSize(new java.awt.Dimension(700, 200));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cuadros", "Libros", "Música", "Videojuegos" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(86, 220, 87, 0);
        jPanel3.add(jComboBox2, gridBagConstraints);

        jCheckBox1.setText("Estadisticas");
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(86, 6, 0, 206);
        jPanel3.add(jCheckBox1, gridBagConstraints);

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 212, 680, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setMaximumSize(new java.awt.Dimension(700, 250));
        jPanel2.setMinimumSize(new java.awt.Dimension(700, 250));
        jPanel2.setPreferredSize(new java.awt.Dimension(700, 250));
        jPanel2.setLayout(new java.awt.GridBagLayout());
        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 418, 680, 190));
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
        getChangeEvent(evt);
    }//GEN-LAST:event_jCheckBox1StateChanged

//

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables


    @Override
    public javax.swing.JComboBox getSeleccion(){
        return jComboBox2;
    }
    
    /**
     * Devuelve jCheckBox1 que determina la posibilidad de estadísticas.
     * @return
     */
    public javax.swing.JCheckBox getIsEstadisticas() {
        return jCheckBox1;
    }
    
    /**
     * Indica si está marcada la opción de estadísticas.
     */
    public void setIsEstadisticas() {
        jCheckBox1.setSelected(true);
    }
    
    /**
     * Marca como falso el jCheckBox1.
     */
    public void setNotEstadisticas() {
        jCheckBox1.setSelected(false);
    }
    
    /**
     * Asigna el tipo al jComboBox2.
     * @param tipo
     */
    public void setTipo(int tipo) {
        jComboBox2.setSelectedIndex(tipo);
    }
        
    /**
     * Indica si el jCheckBox1, que determina las estadísticas, está marcado.
     * @return
     */
    public boolean getEstadisticas(){
        return jCheckBox1.isSelected(); 
    }
}
