/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package catalogador;

import BibliotecaRIGU.JSimpleDialog;
import java.awt.Image;

/**
 * Clase de la GUI de los artículos que se comparan.
 * @author DiegoBergondo
 */
public class pantallaComparado extends JSimpleDialog {
    
    /**
     * Creates new form pantallaComparado
     */
    public pantallaComparado() {
        super();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setMaximumSize(new java.awt.Dimension(200, 170));
        setMinimumSize(new java.awt.Dimension(200, 170));
        setPreferredSize(new java.awt.Dimension(200, 170));
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(340, 65));
        jPanel1.setPreferredSize(new java.awt.Dimension(340, 65));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jTextField1.setText("Precio pagado");
        jTextField1.setMinimumSize(new java.awt.Dimension(240, 26));
        jTextField1.setPreferredSize(new java.awt.Dimension(240, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        jPanel1.add(jTextField1, gridBagConstraints);

        jTextField6.setText("Precio de venta");
        jTextField6.setMinimumSize(new java.awt.Dimension(240, 26));
        jTextField6.setPreferredSize(new java.awt.Dimension(240, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 14, 0);
        jPanel1.add(jTextField6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 11);
        add(jPanel1, gridBagConstraints);

        jPanel3.setMinimumSize(new java.awt.Dimension(180, 120));
        jPanel3.setPreferredSize(new java.awt.Dimension(180, 120));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jTextField2.setText("Titulo");
        jTextField2.setMinimumSize(new java.awt.Dimension(150, 26));
        jTextField2.setPreferredSize(new java.awt.Dimension(150, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 14);
        jPanel3.add(jTextField2, gridBagConstraints);

        jTextField3.setText("Autor");
        jTextField3.setMinimumSize(new java.awt.Dimension(150, 26));
        jTextField3.setPreferredSize(new java.awt.Dimension(150, 26));
        jTextField3.setSize(new java.awt.Dimension(150, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 14);
        jPanel3.add(jTextField3, gridBagConstraints);

        jTextField4.setText("Formato");
        jTextField4.setMinimumSize(new java.awt.Dimension(150, 26));
        jTextField4.setPreferredSize(new java.awt.Dimension(150, 26));
        jTextField4.setSize(new java.awt.Dimension(150, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 14);
        jPanel3.add(jTextField4, gridBagConstraints);

        jTextField5.setText("Estado");
        jTextField5.setMinimumSize(new java.awt.Dimension(150, 26));
        jTextField5.setPreferredSize(new java.awt.Dimension(150, 26));
        jTextField5.setSize(new java.awt.Dimension(150, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 14);
        jPanel3.add(jTextField5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        add(jPanel3, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/no-image-icon2.png"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(142, 108));
        jLabel1.setPreferredSize(new java.awt.Dimension(142, 108));
        jLabel1.setSize(new java.awt.Dimension(142, 108));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel2.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 11);
        add(jPanel2, gridBagConstraints);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Ganancia prevista frente a media"));
        jPanel4.setMinimumSize(new java.awt.Dimension(337, 50));
        jPanel4.setPreferredSize(new java.awt.Dimension(337, 50));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jProgressBar1.setMinimum(-100);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 304;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 12, 11);
        jPanel4.add(jProgressBar1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 11);
        add(jPanel4, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

//

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

    /**
     * Devuelve el jTextField1.
     * @return
     */
    public javax.swing.JTextField getTexto(){
    return this.jTextField1;
}

    /**
     * Asigna al jTextField2 el texto introducido por parámetro.
     * @param texto
     */
    public void setTitulo(String texto){
    this.jTextField2.setText(texto);
}

    /**
     * Asigna al jTextField3 el texto introducido por parámetro.
     * @param texto
     */
    public void setAutor(String texto){
    this.jTextField3.setText(texto);
}

    /**
     * Asigna al jTextField4 el texto introducido por parámetro.
     * @param texto
     */
    public void setFormato(String texto){
    this.jTextField4.setText(texto);
}

    /**
     * Asigna al jTextField5 el texto introducido por parámetro.
     * @param texto
     */
    public void setEstado(String texto){
    this.jTextField5.setText(texto);
}

    /**
     * Asigna al jTextField1 el número introducido por parámetro.
     * @param precioP
     */
    public void setPrecioPagado(int precioP){
    this.jTextField1.setText(String.valueOf(precioP));
}

    /**
     * Asigna al jTextField6 el número introducido por parámetro.
     * @param precioV
     */
    public void setPrecioVenta(int precioV){
    this.jTextField6.setText(String.valueOf(precioV));
}

    /**
     * Asigna al jLabel1 la imagen introducida por parámetro.
     * @param imagen
     */
    public void setImagen(Image imagen) {
    Image captura = imagen.getScaledInstance(140, 105, Image.SCALE_DEFAULT);
    this.jLabel1.setIcon(new javax.swing.ImageIcon(captura));
}

    /**
     * Asigna al jProgressBar1 el valor introducido por parámetro.
     * @param gan
     */
    public void setGanancia (int gan){
    this.jProgressBar1.setValue(gan);
}

}